name: Send iOS artifact to Appetize
on:
  push:
    branches:
      - main
concurrency:
  group: ios
  cancel-in-progress: true
jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: 15.4
      - run: xcodebuild -configuration Debug -sdk iphonesimulator DEVELOPMENT_TEAM=SKMME9E2Y8 CODE_SIGNING_ALLOWED=NO build
        working-directory: ios
      - run: zip -r SpotNotes.zip build/Debug-iphonesimulator/SpotNotes.app
        working-directory: ios
      - uses: appetizeio/github-action-appetize@v1.0.3
        with:
          apiToken: ${{ secrets.APPETIZE_API_TOKEN }}
          appFile: ios/SpotNotes.zip
          platform: 'ios'
